In [1]:

import os, types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.
cos_client = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='ZVLMFinOftXKKjsKSujLUG_ToupIKGM_MS4CoReqGR-h',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.private.us.cloud-object-storage.appdomain.cloud')

bucket = 'cardamageclassification1-donotdelete-pr-nqupisqo70cjxd'
object_key = 'Dataset.zip'

streaming_body_2 = cos_client.get_object(Bucket=bucket, Key=object_key)['Body']

# Your data file was loaded into a botocore.response.StreamingBody object.
# Please read the documentation of ibm_boto3 and pandas to learn more about the possibilities to load the data.
# ibm_boto3 documentation: https://ibm.github.io/ibm-cos-sdk-python/
# pandas documentation: http://pandas.pydata.org/


In [2]:
from io import BytesIO
import zipfile
unzip=zipfile.ZipFile(BytesIO(streaming_body_2.read()),'r')
file_paths=unzip.namelist()
for path in file_paths:
    unzip.extract(path)

In [3]:
pwd

'/home/wsuser/work'

In [4]:
ls

'Car damage'/


In [5]:
import tensorflow

In [6]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator


In [7]:
train_datagen =ImageDataGenerator(rescale=1./255,horizontal_flip=True,vertical_flip=True,zoom_range =0.2)

In [8]:
test_datagen=ImageDataGenerator(rescale=1./255)

In [9]:
training_set=train_datagen.flow_from_directory(r"Car damage/body/training",target_size=(64,64),class_mode="categorical",batch_size=24)

Found 979 images belonging to 3 classes.


In [10]:
test_set=test_datagen.flow_from_directory(r"Car damage/body/validation",target_size=(64,64),class_mode="categorical",batch_size=24)

Found 171 images belonging to 3 classes.


In [11]:
training_set1=train_datagen.flow_from_directory(r"Car damage/level/training",target_size=(64,64),class_mode="categorical",batch_size=24)

Found 979 images belonging to 3 classes.


In [12]:
test_set1=train_datagen.flow_from_directory(r"Car damage/level/validation",target_size=(64,64),class_mode="categorical",batch_size=24)

Found 171 images belonging to 3 classes.


model building

In [13]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Convolution2D,MaxPooling2D,Flatten,Dense

In [14]:
model = Sequential()

In [15]:
model1=Sequential()

In [16]:
model.add(Convolution2D(32,(3,3),activation ="relu",input_shape = (64,64,3)))

In [17]:
model.add(MaxPooling2D(pool_size=(2,2)))

In [18]:
model.add(Flatten())

In [19]:
model.add(Dense(300,activation = 'relu'))

In [20]:
model.add(Dense(300,activation = 'relu'))

In [21]:
model.add(Dense(3,activation="softmax"))

In [22]:
model.compile(loss="categorical_crossentropy",metrics=["accuracy"],optimizer='adam')

In [23]:
model1.add(Convolution2D(32,(3,3),activation ="relu",input_shape = (64,64,3)))
model1.add(MaxPooling2D(pool_size=(2,2)))
model1.add(Flatten())
model1.add(Dense(300,activation = 'relu'))
model1.add(Dense(300,activation = 'relu'))
model1.add(Dense(3,activation="softmax"))
model1.compile(loss="categorical_crossentropy",metrics=["accuracy"],optimizer='adam')

In [24]:
len(training_set)

41

In [25]:
import sys
# fit the model
r = model.fit_generator(training_set,validation_data=test_set,epochs=5,steps_per_epoch=len(training_set),validation_steps=len(test_set))

/tmp/wsuser/ipykernel_164/333018792.py:3: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  r = model.fit_generator(training_set,validation_data=test_set,epochs=5,steps_per_epoch=len(training_set),validation_steps=len(test_set))


Epoch 1/5
41/41 [==============================] - 7s 171ms/step - loss: 1.2694 - accuracy: 0.3739 - val_loss: 1.1018 - val_accuracy: 0.2982
Epoch 2/5
41/41 [==============================] - 7s 163ms/step - loss: 1.0843 - accuracy: 0.4137 - val_loss: 1.0886 - val_accuracy: 0.4269
Epoch 3/5
41/41 [==============================] - 7s 162ms/step - loss: 1.0650 - accuracy: 0.4372 - val_loss: 1.1530 - val_accuracy: 0.4211
Epoch 4/5
41/41 [==============================] - 7s 164ms/step - loss: 1.0442 - accuracy: 0.4617 - val_loss: 1.0952 - val_accuracy: 0.4386
Epoch 5/5
41/41 [==============================] - 7s 165ms/step - loss: 1.0265 - accuracy: 0.4821 - val_loss: 1.0543 - val_accuracy: 0.4912


In [26]:
import sys
# fit the model
r = model1.fit_generator(training_set1,validation_data=test_set1,epochs=5,steps_per_epoch=len(training_set1),validation_steps=len(test_set1))

Epoch 1/5


/tmp/wsuser/ipykernel_164/3740016893.py:3: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  r = model1.fit_generator(training_set1,validation_data=test_set1,epochs=5,steps_per_epoch=len(training_set1),validation_steps=len(test_set1))


41/41 [==============================] - 8s 174ms/step - loss: 1.6360 - accuracy: 0.3851 - val_loss: 1.0731 - val_accuracy: 0.4561
Epoch 2/5
41/41 [==============================] - 7s 168ms/step - loss: 1.0758 - accuracy: 0.4096 - val_loss: 1.0499 - val_accuracy: 0.4503
Epoch 3/5
41/41 [==============================] - 7s 168ms/step - loss: 1.0118 - accuracy: 0.4903 - val_loss: 1.1129 - val_accuracy: 0.3801
Epoch 4/5
41/41 [==============================] - 7s 164ms/step - loss: 0.9873 - accuracy: 0.4995 - val_loss: 1.0894 - val_accuracy: 0.4327
Epoch 5/5
41/41 [==============================] - 7s 170ms/step - loss: 0.9503 - accuracy: 0.5240 - val_loss: 0.9928 - val_accuracy: 0.5497


In [27]:
model.save("car_damage.h5")

In [28]:
model1.save("car_damage1.h5")

In [29]:
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
import numpy as np

In [30]:
model = load_model("car_damage.h5")

In [31]:
model1 = load_model("car_damage1.h5")

In [32]:
#compressing the file
!tar -zcvf cardamage-classification-model.tgz car_damage.h5

car_damage.h5


In [33]:

!tar -zcvf cardamage1-classification-model.tgz car_damage1.h5


car_damage1.h5


# Deployement space

In [34]:
!pip install ibm_watson_machine_learning

In [35]:
!pip install watson-machine-learning-client --upgrade

     |████████████████████████████████| 538 kB 10.0 MB/s eta 0:00:01


In [36]:
from ibm_watson_machine_learning import APIClient

In [37]:
wml_credentials = {
    "url":"https://us-south.ml.cloud.ibm.com",
    "apikey":"CGd8BXsAb9Oue-V7PS_3vV_dSkAxtYrhoiBm2H7s6Rr1"
}

In [38]:
client = APIClient(wml_credentials)

In [39]:
client

In [40]:
client.spaces.list()

Note: 'limit' is not provided. Only first 50 records will be displayed if the number of records exceed 50
------------------------------------  ----------  ------------------------
ID                                    NAME        CREATED
70e0d04f-6087-4bd4-b476-6493ad5a98cb  car_damage  2022-11-14T09:09:01.154Z
------------------------------------  ----------  ------------------------


In [41]:
space_id="70e0d04f-6087-4bd4-b476-6493ad5a98cb"

In [42]:
client.set.default_space(space_id)

'SUCCESS'

In [43]:
client.software_specifications.list()

-----------------------------  ------------------------------------  ----
NAME                           ASSET_ID                              TYPE
default_py3.6                  0062b8c9-8b7d-44a0-a9b9-46c416adcbd9  base
kernel-spark3.2-scala2.12      020d69ce-7ac1-5e68-ac1a-31189867356a  base
pytorch-onnx_1.3-py3.7-edt     069ea134-3346-5748-b513-49120e15d288  base
scikit-learn_0.20-py3.6        09c5a1d0-9c1e-4473-a344-eb7b665ff687  base
spark-mllib_3.0-scala_2.12     09f4cff0-90a7-5899-b9ed-1ef348aebdee  base
pytorch-onnx_rt22.1-py3.9      0b848dd4-e681-5599-be41-b5f6fccc6471  base
ai-function_0.1-py3.6          0cdb0f1e-5376-4f4d-92dd-da3b69aa9bda  base
shiny-r3.6                     0e6e79df-875e-4f24-8ae9-62dcc2148306  base
tensorflow_2.4-py3.7-horovod   1092590a-307d-563d-9b62-4eb7d64b3f22  base
pytorch_1.1-py3.6              10ac12d6-6b30-4ccd-8392-3e922c096a92  base
tensorflow_1.15-py3.6-ddl      111e41b3-de2d-5422-a4d6-bf776828c4b7  base
autoai-kb_rt22.2-py3.10        125b6d9

In [44]:
software_space_uid = client.software_specifications.get_id_by_name("tensorflow_rt22.1-py3.9")

In [45]:
software_space_uid

'acd9c798-6974-5d2f-a657-ce06e986df4d'

In [46]:
model_details = client.repository.store_model(model='cardamage-classification-model.tgz',meta_props={
    client.repository.ModelMetaNames.NAME:"cnn model",
    client.repository.ModelMetaNames.TYPE:"tensorflow_2.7",
    client.repository.ModelMetaNames.SOFTWARE_SPEC_UID:software_space_uid
})

In [47]:
model_id=client.repository.get_model_id(model_details)

In [48]:
model_id

'3b6981f6-5524-47cb-93af-ef34e94520a7'

In [49]:
client.repository.download(model_id,'my_model.tar.gz')

Successfully saved model content to file: 'my_model.tar.gz'


'/home/wsuser/work/my_model.tar.gz'

In [50]:
model_details1 = client.repository.store_model(model='cardamage1-classification-model.tgz',meta_props={
    client.repository.ModelMetaNames.NAME:"cnn model",
    client.repository.ModelMetaNames.TYPE:"tensorflow_2.7",
    client.repository.ModelMetaNames.SOFTWARE_SPEC_UID:software_space_uid
})

In [51]:
model_id1=client.repository.get_model_id(model_details1)

In [52]:
model_id1

'dda611fe-2806-40d2-a74a-07d6e9c3241c'

In [53]:
from keras.models import load_model
from keras.preprocessing import image

In [54]:
model = load_model("car_damage.h5")

In [55]:
model1 = load_model("car_damage1.h5")

In [58]:
img = image.load_img("Car damage/body/training/00-front/0001.jpeg",target_size=(64,64))

AttributeError: 'Sequential' object has no attribute 'predict_classes'

In [59]:
img1 = image.load_img("Car damage/level/validation/02-moderate/0035.JPEG",target_size=(64,64))

In [61]:
x= image.img_to_array(img)

In [62]:
x

array([[[254., 255., 250.],
        [254., 255., 248.],
        [254., 255., 246.],
        ...,
        [251., 255., 240.],
        [248., 251., 244.],
        [252., 255., 246.]],

       [[ 19.,  22.,  11.],
        [ 26.,  30.,  16.],
        [ 43.,  47.,  30.],
        ...,
        [ 80., 101.,  22.],
        [ 86., 106.,  34.],
        [ 56.,  76.,   4.]],

       [[ 17.,  21.,   6.],
        [ 29.,  33.,  16.],
        [ 25.,  30.,   8.],
        ...,
        [ 84., 109.,  41.],
        [ 57.,  82.,  16.],
        [ 88., 113.,  48.]],

       ...,

       [[153., 146., 130.],
        [144., 138., 124.],
        [166., 162., 150.],
        ...,
        [103., 102., 108.],
        [133., 128., 125.],
        [129., 124., 121.]],

       [[144., 138., 126.],
        [130., 126., 115.],
        [142., 139., 130.],
        ...,
        [ 83.,  82.,  88.],
        [171., 166., 163.],
        [129., 124., 121.]],

       [[255., 250., 244.],
        [249., 244., 240.],
        [255., 2

In [80]:
x1 = image.img_to_array(img1)

In [81]:
x1

array([[[ 23.,  21.,  22.],
        [ 23.,  21.,  22.],
        [ 23.,  21.,  22.],
        ...,
        [128., 137., 134.],
        [129., 138., 135.],
        [132., 141., 138.]],

       [[ 19.,  17.,  18.],
        [ 19.,  17.,  18.],
        [ 25.,  23.,  24.],
        ...,
        [126., 135., 132.],
        [128., 137., 134.],
        [130., 139., 136.]],

       [[ 21.,  19.,  20.],
        [ 21.,  19.,  20.],
        [ 22.,  20.,  21.],
        ...,
        [124., 133., 130.],
        [126., 135., 132.],
        [129., 138., 135.]],

       ...,

       [[247., 247., 247.],
        [247., 247., 247.],
        [246., 246., 246.],
        ...,
        [248., 248., 248.],
        [249., 249., 249.],
        [251., 251., 251.]],

       [[247., 247., 247.],
        [247., 247., 247.],
        [247., 247., 247.],
        ...,
        [248., 248., 248.],
        [249., 249., 249.],
        [251., 251., 251.]],

       [[247., 247., 247.],
        [247., 247., 247.],
        [248., 2

In [65]:
x = np.expand_dims(x,axis=0)

In [67]:
pred=model.predict(x)

In [68]:
pred

array([[1., 0., 0.]], dtype=float32)

In [74]:
lebels = ["00-front","01-rear","02-side"]

In [75]:
lebels[0]

'00-front'

In [82]:
pred = model.predict(x1)

ValueError: in user code:

    File "/opt/conda/envs/Python-3.9/lib/python3.9/site-packages/keras/engine/training.py", line 1621, in predict_function  *
        return step_function(self, iterator)
    File "/opt/conda/envs/Python-3.9/lib/python3.9/site-packages/keras/engine/training.py", line 1611, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/opt/conda/envs/Python-3.9/lib/python3.9/site-packages/keras/engine/training.py", line 1604, in run_step  **
        outputs = model.predict_step(data)
    File "/opt/conda/envs/Python-3.9/lib/python3.9/site-packages/keras/engine/training.py", line 1572, in predict_step
        return self(x, training=False)
    File "/opt/conda/envs/Python-3.9/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "/opt/conda/envs/Python-3.9/lib/python3.9/site-packages/keras/engine/input_spec.py", line 263, in assert_input_compatibility
        raise ValueError(f'Input {input_index} of layer "{layer_name}" is '

    ValueError: Input 0 of layer "sequential" is incompatible with the layer: expected shape=(None, 64, 64, 3), found shape=(32, 64, 3)


In [83]:
x1 = np.expand_dims(x1,axis = 0)

In [84]:
pred_1 = model1.predict(x1)

In [85]:
pred_1

array([[0., 0., 1.]], dtype=float32)

In [ ]:
lebels = []