# Basic Python

## 1. Split this string

In [2]:
s = "Hi there Sam!"

In [4]:
x=s.split()
print(x)


['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [5]:
planet = "Earth"
diameter = 12742

In [6]:
txt = "The diameter of {} is kilometer."
print(txt)

The diameter of {} is kilometer.


## 3. In this nest dictionary grab the word "hello"

In [7]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [8]:
print(d['k1'][3]["tricky"][3]['target'][3])

hello


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [18]:

array1 = np.zeros(10)
print(array1)
array2 = np.ones(10)*5
print(array2)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [15]:
import numpy as np
array = np.arange(20,35,2)
print(" The even integers from 20 to 30 are:")
print(array)

 The even integers from 20 to 30 are:
[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [17]:
import numpy as np
x = np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [21]:
import numpy as np
a = np.array ([1,2,3])
b = np.array([4,5,6])
np.concatenate((a,b), axis = 0)



array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [22]:
import pandas as pd


In [24]:
data = [['akash',25], ['sweta',23], ['shivam',26]]

df = pd.DataFrame(data, columns=['Name', 'Age'])

df


Name  Age
0   akash   25
1   sweta   23
2  shivam   26

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [30]:
import pandas as pd 

#creating range sequence of dates
dates = pd.date_range('01-01-2023', periods=10,)

#creating pandas series with date index
s = pd.Series(dates)
print (s)

0   2023-01-01
1   2023-01-02
2   2023-01-03
3   2023-01-04
4   2023-01-05
5   2023-01-06
6   2023-01-07
7   2023-01-08
8   2023-01-09
9   2023-01-10
dtype: datetime64[ns]


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [37]:
lists = [[1,'aaa',22],[2,'bbb',25],[3,'ccc',24]]

import pandas as pd

#creating df object with columns specified
df = pd.DataFrame(lists, columns =['Serial', 'Name','Age'])
print(df)

   Serial Name  Age
0       1  aaa   22
1       2  bbb   25
2       3  ccc   24
